import { Dispatch, SetStateAction } from "react";

export interface CategoriesProps {
  setCategoryBannerProps: Dispatch<SetStateAction<{ name: string, img: string }>>,
  setDealsCat: Dispatch<SetStateAction<boolean>>, 
  setBestEatCat: Dispatch<SetStateAction<boolean>>,
  setAlcoholCat: Dispatch<SetStateAction<boolean>>,
  setBurgerCat: Dispatch<SetStateAction<boolean>>,
  setChineseCat: Dispatch<SetStateAction<boolean>>,
  setSandwichCat: Dispatch<SetStateAction<boolean>>,
  setThaiCat: Dispatch<SetStateAction<boolean>>,
  setSushiCat: Dispatch<SetStateAction<boolean>>,
  setDessertCat: Dispatch<SetStateAction<boolean>>,
  setAsiaCat: Dispatch<SetStateAction<boolean>>,
  setAmericanCat: Dispatch<SetStateAction<boolean>>,
  setGeneralStuffCat: Dispatch<SetStateAction<boolean>>,
  setAnimalCareCat: Dispatch<SetStateAction<boolean>>,
  setHealthyCat: Dispatch<SetStateAction<boolean>>,
  setFastFoodCat: Dispatch<SetStateAction<boolean>>,
  setPizzaCat: Dispatch<SetStateAction<boolean>>,
  setKoreanCat: Dispatch<SetStateAction<boolean>>,
  setIndianCat: Dispatch<SetStateAction<boolean>>,
} 

export interface MealChooseProps {
  dealsCat: boolean,
  bestEatCat: boolean,
  alcoholCat: boolean,
  burgerCat: boolean,
  chineseCat: boolean,
  thaiCat: boolean,
  sandwichCat: boolean,
  sushiCat: boolean,
  dessertCat: boolean,
  asiaCat: boolean,
  americanCat: boolean,
  generalStuffCat: boolean,
  animalCareCat: boolean,
  healthyCat: boolean,
  fastFoodCat: boolean,
  pizzaCat: boolean,
  koreanCat: boolean,
  indianCat: boolean,
  setDealsCat: Dispatch<SetStateAction<boolean>>, 
  setBestEatCat: Dispatch<SetStateAction<boolean>>,
  setAlcoholCat: Dispatch<SetStateAction<boolean>>,
  setBurgerCat: Dispatch<SetStateAction<boolean>>,
  setChineseCat: Dispatch<SetStateAction<boolean>>,
  setSandwichCat: Dispatch<SetStateAction<boolean>>,
  setThaiCat: Dispatch<SetStateAction<boolean>>,
  setSushiCat: Dispatch<SetStateAction<boolean>>,
  setDessertCat: Dispatch<SetStateAction<boolean>>,
  setAsiaCat: Dispatch<SetStateAction<boolean>>,
  setAmericanCat: Dispatch<SetStateAction<boolean>>,
  setGeneralStuffCat: Dispatch<SetStateAction<boolean>>,
  setAnimalCareCat: Dispatch<SetStateAction<boolean>>,
  setHealthyCat: Dispatch<SetStateAction<boolean>>,
  setFastFoodCat: Dispatch<SetStateAction<boolean>>,
  setPizzaCat: Dispatch<SetStateAction<boolean>>,
  setKoreanCat: Dispatch<SetStateAction<boolean>>,
  setIndianCat: Dispatch<SetStateAction<boolean>>,
}