export interface RestaurantsProps {
  forYouFilter: boolean;
  popularFilter: boolean;
  ratingFilter: boolean;
  uberEatsFilter: boolean;
  oneEURFilter: boolean;
  twoEURFilter: boolean;
  threeEURFilter: boolean;
  fourEURFilter: boolean;
  veggyFilter: boolean;
  veganFilter: boolean;
  glutenFreeFilter: boolean;
  dealsCat: boolean,
  bestEatCat: boolean,
  alcoholCat: boolean,
  burgerCat: boolean,
  chineseCat: boolean,
  thaiCat: boolean,
  sandwichCat: boolean,
  sushiCat: boolean,
  dessertCat: boolean,
  asiaCat: boolean,
  americanCat: boolean,
  generalStuffCat: boolean,
  animalCareCat: boolean,
  healthyCat: boolean,
  fastFoodCat: boolean,
  pizzaCat: boolean,
  koreanCat: boolean,
  indianCat: boolean,
}